/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Clases.KardexMovs;
import Clases.ScrollSens;
import Clases.tools;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

public class DashBoard02 extends javax.swing.JPanel {

    public static ArrayList<KardexMovs> movimientos = new ArrayList();
    JPanel x = new JPanel();
    String mes = "Enero";
    public static int opcion = 1;
    static Date rango01 = new Date();
    static Date rango02 = new Date();

    public DashBoard02() {
        initComponents();
        x.setBackground(new Color(59, 59, 59));
        scroll.setViewportView(x);
        new ScrollSens(scroll, 75);
        fecha01.setDatoFecha(new Date());
        fecha02.setDatoFecha(new Date());
        calcularRangos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesGroupRadio = new javax.swing.ButtonGroup();
        panelCentral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rSPanelVector1 = new rojeru_san.rspanel.RSPanelVector();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mayorRotacionBtn = new RSComponentShade.RSButtonRippleShade();
        scroll = new javax.swing.JScrollPane();
        mesRadioBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        mesCombo = new rojerusan.RSComboBox();
        rangoRadioBtn = new javax.swing.JRadioButton();
        fecha01 = new rojeru_san.rsdate.RSDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha02 = new rojeru_san.rsdate.RSDateChooser();
        buscarBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 59, 59));

        panelCentral.setBackground(new java.awt.Color(59, 59, 59));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        rSPanelVector1.setBackground(new java.awt.Color(0, 102, 102));
        rSPanelVector1.setColorBorde(new java.awt.Color(51, 51, 51));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mayor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rotación");

        mayorRotacionBtn.setBackground(new java.awt.Color(0, 102, 102));
        mayorRotacionBtn.setBorder(null);
        mayorRotacionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_eye_40px.png"))); // NOI18N
        mayorRotacionBtn.setBgHover(new java.awt.Color(0, 153, 153));
        mayorRotacionBtn.setContentAreaFilled(true);
        mayorRotacionBtn.setPixels(0);
        mayorRotacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorRotacionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelVector1Layout = new javax.swing.GroupLayout(rSPanelVector1);
        rSPanelVector1.setLayout(rSPanelVector1Layout);
        rSPanelVector1Layout.setHorizontalGroup(
            rSPanelVector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelVector1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelVector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(mayorRotacionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rSPanelVector1Layout.setVerticalGroup(
            rSPanelVector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelVector1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelVector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mayorRotacionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rSPanelVector1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelVector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelVector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mesRadioBtn.setBackground(new java.awt.Color(59, 59, 59));
        opcionesGroupRadio.add(mesRadioBtn);
        mesRadioBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mesRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        mesRadioBtn.setSelected(true);
        mesRadioBtn.setText("Mes Especifico");
        mesRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mesRadioBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mesRadioBtnStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione los Parámetros");

        mesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesCombo.setColorArrow(new java.awt.Color(0, 102, 102));
        mesCombo.setColorFondo(new java.awt.Color(59, 59, 59));
        mesCombo.setColorSeleccion(new java.awt.Color(0, 102, 102));
        mesCombo.setDisabledIdex("");
        mesCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mesComboItemStateChanged(evt);
            }
        });

        rangoRadioBtn.setBackground(new java.awt.Color(59, 59, 59));
        opcionesGroupRadio.add(rangoRadioBtn);
        rangoRadioBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rangoRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        rangoRadioBtn.setText("Rango de Fecha");
        rangoRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rangoRadioBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rangoRadioBtnStateChanged(evt);
            }
        });

        fecha01.setColorBackground(new java.awt.Color(0, 102, 102));
        fecha01.setColorButtonHover(new java.awt.Color(0, 153, 153));
        fecha01.setColorForeground(new java.awt.Color(0, 102, 102));
        fecha01.setFormatoFecha("yyyy-MM-dd");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESDE");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HASTA");

        fecha02.setColorBackground(new java.awt.Color(0, 102, 102));
        fecha02.setColorButtonHover(new java.awt.Color(0, 153, 153));
        fecha02.setColorForeground(new java.awt.Color(0, 102, 102));
        fecha02.setFormatoFecha("yyyy-MM-dd");

        buscarBtn.setBackground(new java.awt.Color(0, 102, 102));
        buscarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_search_32px.png"))); // NOI18N
        buscarBtn.setContentAreaFilled(false);
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarBtnMouseExited(evt);
            }
        });
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCentralLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCentralLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mesRadioBtn)
                                    .addComponent(rangoRadioBtn)
                                    .addGroup(panelCentralLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(mesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCentralLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha02, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCentralLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha01, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                        .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mesRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rangoRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(134, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mayorRotacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorRotacionBtnActionPerformed
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(new Color(59, 59, 59));
        panel.add(new panelPorcentaje("Producto 01", 32690, 18500, 19));
        panel.repaint();
        panel.add(new panelPorcentaje("Producto 02", 32690, 9200, 16));
        panel.repaint();
        scroll.setViewportView(panel);
    }//GEN-LAST:event_mayorRotacionBtnActionPerformed

    private void mesComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mesComboItemStateChanged


    }//GEN-LAST:event_mesComboItemStateChanged

    private void mesRadioBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mesRadioBtnStateChanged
        mesCombo.setEnabled(mesRadioBtn.isSelected());
        opcion = 1;
    }//GEN-LAST:event_mesRadioBtnStateChanged

    private void rangoRadioBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rangoRadioBtnStateChanged
        opcion = 2;
    }//GEN-LAST:event_rangoRadioBtnStateChanged

    private void buscarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseEntered
        buscarBtn.setContentAreaFilled(true);
    }//GEN-LAST:event_buscarBtnMouseEntered

    private void buscarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseExited
        buscarBtn.setContentAreaFilled(false);
    }//GEN-LAST:event_buscarBtnMouseExited

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        calcularRangos();
        setValores();
    }//GEN-LAST:event_buscarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private rojeru_san.rsdate.RSDateChooser fecha01;
    private rojeru_san.rsdate.RSDateChooser fecha02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static RSComponentShade.RSButtonRippleShade mayorRotacionBtn;
    private rojerusan.RSComboBox mesCombo;
    private javax.swing.JRadioButton mesRadioBtn;
    private javax.swing.ButtonGroup opcionesGroupRadio;
    private javax.swing.JPanel panelCentral;
    private rojeru_san.rspanel.RSPanelVector rSPanelVector1;
    private javax.swing.JRadioButton rangoRadioBtn;
    private static javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

    public static void setValores() {
        switch (opcion) {
            case 1:
                /*
                 ArrayList<KardexMovs> listaDesordenada = new ArrayList();
                ArrayList<KardexMovs> listaOrdenada = new ArrayList();
                for (KardexMovs mov : movimientos) {
                    Date fecha = new Date(); //= new SimpleDateFormat("yyyy-MM-dd").parse(mov.getFecha());
                    try {
                        fecha = new SimpleDateFormat("yyyy-MM-dd").parse(mov.getFecha());
                        //String ccc  = new SimpleDateFormat("yyyy-MM-dd").format(fecha);
                        //fecha = new SimpleDateFormat("yyyy-MM-dd").parse(ccc);
                    } catch (ParseException ex) {
                        Logger.getLogger(DashBoard02.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //System.out.println(new SimpleDateFormat("yyyy-MM-dd").format(fecha));
                    // System.out.println("Fecha.Compareto(Rango01): "+fecha.compareTo(rango01));
                    // System.out.println("Fecha.Compareto(Rango02): "+fecha.compareTo(rango02));
                    
                     double actual = 0.0;
                     double cantx = 0.0;
                     double precx = 0.0;
                     double rst = 0.0;
                    if ((fecha.compareTo(rango01) > 0 || fecha.compareTo(rango01) == 0)
                            && (fecha.compareTo(rango02) < 0 || fecha.compareTo(rango02) == 0)) {

                        boolean llave = false;
                        for (KardexMovs movx : listaDesordenada) {
                            if (movx.getCodigo().equals(mov.getCodigo())) {
                                llave = true;
                                movx.setCantidad(movx.getCantidad() + mov.getCantidad());
                               
                                String dd = mov.getNumDocumento().equalsIgnoreCase("Sin Asignar")?"0.0":mov.getNumDocumento();
                               
                                actual = Double.parseDouble(dd);
                                cantx = mov.getCantidad();
                                precx = mov.getPrecioSigv();
                                actual += (cantx*precx);
                               mov.setNumDocumento(actual+"");
                               // String dd = movx.getNumDocumento().equalsIgnoreCase("Sin Asignar")?"0.0":movx.getNumDocumento();
                                //double xf = Double.parseDouble(dd);
                                //movx.setNumDocumento((xf+(mov.getCantidad()*mov.getPrecioSigv()))+"");
                            }
                        }
                        if (llave == false) {
                             cantx = mov.getCantidad();
                             precx = mov.getPrecioSigv();
                             rst = cantx*precx;
                            mov.setNumDocumento(rst+"");
                            listaDesordenada.add(mov);
                        }
                        //  Comparator<KardexMovs> comparador = Collections.reverseOrder();
                        // Collections.sort(listaDesordenada, comparador);

                    }

                }
                int index = 0;
                double  total = 0.0;
                while(listaDesordenada.size()>0){
                    index=0;
                    //System.out.println("Antes ListaDesordenada Size: " + listaDesordenada.size());
                    for (int i = 0; i < listaDesordenada.size(); i++) {
                        if (listaDesordenada.get(i).getCantidad() > listaDesordenada.get(index).getCantidad()) {
                            index = i;
                        }
                    }
                    listaOrdenada.add(listaDesordenada.get(index));
                    total+=listaDesordenada.get(index).getCantidad();
                    listaDesordenada.remove(index);
                    //System.out.println("Despues ListaDesordenada Size: " + listaDesordenada.size());
                }
                
                JPanel panel = new JPanel();
                panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                panel.setBackground(new Color(59,59,59));
                for (KardexMovs mc : listaOrdenada) {
                   String dd = mc.getNumDocumento().equalsIgnoreCase("Sin Asignar")?"0":mc.getNumDocumento();
                   dd = dd.equals("0.0")?"0":dd;
                    double xf = Double.parseDouble(dd);
                                
                    panel.add(new panelPorcentaje(mc.getNombre(),total,mc.getCantidad(),(int)xf));
                    panel.repaint();
                }   
                scroll.setViewportView(panel);
                */
                
               
                break;
            case 2:
                break;
        }
    }

    public static void setMovimientos(ArrayList lista) {
        movimientos = (ArrayList) lista.clone();
        //DashBoard02.setValores();
    }

    private void calcularRangos() {
        try {
            String medddd = new SimpleDateFormat("MMMM").format(new Date());
            int mx = new tools().getMes(medddd);
            mesCombo.setSelectedIndex(mx);

            int mesSeleccionado = mesCombo.getSelectedIndex();//aumentar 1 para ser mes actual
            mes = new tools().getMes(mesSeleccionado);

            SimpleDateFormat getYearFormat = new SimpleDateFormat("yyyy");
            String currentYear = getYearFormat.format(new Date());
            String tempFecha01 = currentYear + "-" + mesSeleccionado + "-01";

            Date fx = new SimpleDateFormat("yyyy-MM-dd").parse(tempFecha01);
            Calendar cal = Calendar.getInstance();
            cal.setTime(fx);
            String tempFecha02 = currentYear + "-" + mesSeleccionado + "-" + cal.getActualMaximum(Calendar.DAY_OF_MONTH);

            rango01 = new SimpleDateFormat("yyyy-MM-dd").parse(tempFecha01);
            rango02 = new SimpleDateFormat("yyyy-MM-dd").parse(tempFecha02);
        } catch (ParseException ex) {
            Logger.getLogger(DashBoard02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
