
package Panels;

import javax.swing.table.DefaultTableModel;


public class tablaPanel extends javax.swing.JPanel {

    /**
     * Creates new form tablaPanel
     */
    public tablaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new rojerusan.RSTableMetro();

        jScrollPane1.setAutoscrolls(true);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "T.Unidad", "Stock", "Precio S/.", "Valorizado", "Estado", "Familia", "Talla", "Tela", "Gramaje", "Últ. Modificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla2.setBackgoundHead(new java.awt.Color(148, 34, 36));
        tabla2.setBackgoundHover(new java.awt.Color(0, 102, 102));
        tabla2.setColorBorderHead(new java.awt.Color(59, 59, 59));
        tabla2.setColorBorderRows(new java.awt.Color(59, 59, 59));
        tabla2.setColorSecondary(new java.awt.Color(255, 255, 255));
        tabla2.setEffectHover(true);
        tabla2.setGridColor(new java.awt.Color(59, 59, 59));
        tabla2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla2);
        if (tabla2.getColumnModel().getColumnCount() > 0) {
            tabla2.getColumnModel().getColumn(0).setMinWidth(80);
            tabla2.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabla2.getColumnModel().getColumn(0).setMaxWidth(100);
            tabla2.getColumnModel().getColumn(1).setMinWidth(120);
            tabla2.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabla2.getColumnModel().getColumn(2).setMinWidth(80);
            tabla2.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabla2.getColumnModel().getColumn(2).setMaxWidth(120);
            tabla2.getColumnModel().getColumn(3).setMinWidth(80);
            tabla2.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabla2.getColumnModel().getColumn(3).setMaxWidth(100);
            tabla2.getColumnModel().getColumn(4).setMinWidth(110);
            tabla2.getColumnModel().getColumn(4).setPreferredWidth(110);
            tabla2.getColumnModel().getColumn(4).setMaxWidth(120);
            tabla2.getColumnModel().getColumn(5).setMinWidth(140);
            tabla2.getColumnModel().getColumn(5).setPreferredWidth(140);
            tabla2.getColumnModel().getColumn(5).setMaxWidth(160);
            tabla2.getColumnModel().getColumn(6).setMinWidth(95);
            tabla2.getColumnModel().getColumn(6).setPreferredWidth(95);
            tabla2.getColumnModel().getColumn(6).setMaxWidth(115);
            tabla2.getColumnModel().getColumn(7).setMinWidth(130);
            tabla2.getColumnModel().getColumn(7).setPreferredWidth(130);
            tabla2.getColumnModel().getColumn(7).setMaxWidth(150);
            tabla2.getColumnModel().getColumn(8).setMinWidth(80);
            tabla2.getColumnModel().getColumn(8).setPreferredWidth(80);
            tabla2.getColumnModel().getColumn(8).setMaxWidth(90);
            tabla2.getColumnModel().getColumn(9).setMinWidth(95);
            tabla2.getColumnModel().getColumn(9).setPreferredWidth(95);
            tabla2.getColumnModel().getColumn(9).setMaxWidth(120);
            tabla2.getColumnModel().getColumn(10).setMinWidth(90);
            tabla2.getColumnModel().getColumn(10).setPreferredWidth(90);
            tabla2.getColumnModel().getColumn(10).setMaxWidth(120);
            tabla2.getColumnModel().getColumn(11).setMinWidth(120);
            tabla2.getColumnModel().getColumn(11).setPreferredWidth(120);
            tabla2.getColumnModel().getColumn(11).setMaxWidth(145);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla2MouseClicked
       int fila = tabla2.getSelectedRow();
        if(evt.getClickCount()==2 && fila>-1){
           InventarioPanel.editBtn.doClick();
       }
    }//GEN-LAST:event_tabla2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public rojerusan.RSTableMetro tabla2;
    // End of variables declaration//GEN-END:variables
}
