/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Clases.ConectarCloudcPanel;
import Frames.UsuarioFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyFade;

public class UsuariosPanel extends javax.swing.JPanel {

    static tablaPanel ptabla = new tablaPanel();
    UsuarioFrame uframe = new UsuarioFrame();
    static String estadox = "";
    
  static int todos=0;
  static int activos=0;
  static int bloqueados=0;
    public UsuariosPanel() {
        initComponents();
        new Thread(this::ini).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTotalUsuarios = new rojeru_san.rspanel.RSPanelVector();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        totalUserTxt = new javax.swing.JLabel();
        panelUsuariosActivos = new rojeru_san.rspanel.RSPanelVector();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        userActivosTxt = new javax.swing.JLabel();
        panelUsuariosBloqueados = new rojeru_san.rspanel.RSPanelVector();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        userBloqueadosTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        estadoCombo = new rojerusan.RSComboBox();
        nombreTxt = new javax.swing.JTextField();
        buscarBtn = new rojeru_san.rsbutton.RSButtonEffect();
        panelBotones = new javax.swing.JPanel();
        rSButtonEffect4 = new rojeru_san.rsbutton.RSButtonEffect();
        editBtn = new rojeru_san.rsbutton.RSButtonEffect();
        agregarBtn = new rojeru_san.rsbutton.RSButtonEffect();

        setBackground(new java.awt.Color(59, 59, 59));

        panelTotalUsuarios.setColorBorde(new java.awt.Color(59, 59, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_Users_30px.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Usuarios: ");

        totalUserTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalUserTxt.setForeground(new java.awt.Color(255, 255, 255));
        totalUserTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalUserTxt.setText("100");

        javax.swing.GroupLayout panelTotalUsuariosLayout = new javax.swing.GroupLayout(panelTotalUsuarios);
        panelTotalUsuarios.setLayout(panelTotalUsuariosLayout);
        panelTotalUsuariosLayout.setHorizontalGroup(
            panelTotalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalUsuariosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalUsuariosLayout.setVerticalGroup(
            panelTotalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTotalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(totalUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelUsuariosActivos.setBackground(new java.awt.Color(0, 204, 0));
        panelUsuariosActivos.setColorBorde(new java.awt.Color(59, 59, 59));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_checkmark_30px.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuarios Activos:");

        userActivosTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userActivosTxt.setForeground(new java.awt.Color(255, 255, 255));
        userActivosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userActivosTxt.setText("90");

        javax.swing.GroupLayout panelUsuariosActivosLayout = new javax.swing.GroupLayout(panelUsuariosActivos);
        panelUsuariosActivos.setLayout(panelUsuariosActivosLayout);
        panelUsuariosActivosLayout.setHorizontalGroup(
            panelUsuariosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosActivosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userActivosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsuariosActivosLayout.setVerticalGroup(
            panelUsuariosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosActivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuariosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(userActivosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelUsuariosBloqueados.setBackground(new java.awt.Color(255, 51, 0));
        panelUsuariosBloqueados.setColorBorde(new java.awt.Color(59, 59, 59));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_lock_30px_1.png"))); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuarios Bloqueados");

        userBloqueadosTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userBloqueadosTxt.setForeground(new java.awt.Color(255, 255, 255));
        userBloqueadosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userBloqueadosTxt.setText("10");

        javax.swing.GroupLayout panelUsuariosBloqueadosLayout = new javax.swing.GroupLayout(panelUsuariosBloqueados);
        panelUsuariosBloqueados.setLayout(panelUsuariosBloqueadosLayout);
        panelUsuariosBloqueadosLayout.setHorizontalGroup(
            panelUsuariosBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosBloqueadosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userBloqueadosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsuariosBloqueadosLayout.setVerticalGroup(
            panelUsuariosBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosBloqueadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuariosBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(userBloqueadosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre / Apellido:");

        jScrollPane1.setAutoscrolls(true);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Código", "Nombre", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setBackgoundHead(new java.awt.Color(148, 34, 36));
        tabla.setBackgoundHover(new java.awt.Color(139, 183, 240));
        tabla.setColorBorderHead(new java.awt.Color(59, 59, 59));
        tabla.setColorBorderRows(new java.awt.Color(59, 59, 59));
        tabla.setColorSecondary(new java.awt.Color(255, 255, 255));
        tabla.setGridColor(new java.awt.Color(59, 59, 59));
        tabla.setSelectionBackground(new java.awt.Color(194, 232, 255));
        tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(80);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabla.getColumnModel().getColumn(0).setMaxWidth(80);
            tabla.getColumnModel().getColumn(1).setMinWidth(120);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabla.getColumnModel().getColumn(1).setMaxWidth(140);
            tabla.getColumnModel().getColumn(3).setMinWidth(120);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabla.getColumnModel().getColumn(3).setMaxWidth(140);
        }

        estadoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija el Estado", "Activo", "Bloqueado", "Todos" }));
        estadoCombo.setColorArrow(new java.awt.Color(39, 39, 39));
        estadoCombo.setColorBorde(new java.awt.Color(255, 255, 255));
        estadoCombo.setColorFondo(new java.awt.Color(59, 59, 59));
        estadoCombo.setColorSeleccion(new java.awt.Color(39, 39, 39));
        estadoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoComboItemStateChanged(evt);
            }
        });

        nombreTxt.setBackground(new java.awt.Color(59, 59, 59));
        nombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        nombreTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        buscarBtn.setBackground(new java.awt.Color(59, 59, 59));
        buscarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_search_32px.png"))); // NOI18N
        buscarBtn.setColorHover(new java.awt.Color(38, 38, 38));
        buscarBtn.setEfecto(rojeru_san.rsbutton.RSButtonEffect.EFECTO.RIPPLE);
        buscarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buscarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buscarBtn.setIconTextGap(12);
        buscarBtn.setMargin(new java.awt.Insets(2, 6, 2, 14));

        panelBotones.setBackground(new java.awt.Color(59, 59, 59));

        rSButtonEffect4.setBackground(new java.awt.Color(59, 59, 59));
        rSButtonEffect4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_refresh_24px.png"))); // NOI18N
        rSButtonEffect4.setText("Actualizar");
        rSButtonEffect4.setColorHover(new java.awt.Color(38, 38, 38));
        rSButtonEffect4.setEfecto(rojeru_san.rsbutton.RSButtonEffect.EFECTO.RIPPLE);
        rSButtonEffect4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonEffect4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonEffect4.setIconTextGap(12);
        rSButtonEffect4.setMargin(new java.awt.Insets(2, 6, 2, 14));

        editBtn.setBackground(new java.awt.Color(59, 59, 59));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_edit_32px_3.png"))); // NOI18N
        editBtn.setText("Modificar Usuario");
        editBtn.setColorHover(new java.awt.Color(38, 38, 38));
        editBtn.setEfecto(rojeru_san.rsbutton.RSButtonEffect.EFECTO.RIPPLE);
        editBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editBtn.setIconTextGap(12);
        editBtn.setMargin(new java.awt.Insets(2, 6, 2, 14));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        agregarBtn.setBackground(new java.awt.Color(59, 59, 59));
        agregarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_add_32px.png"))); // NOI18N
        agregarBtn.setText("Agregar Usuario");
        agregarBtn.setColorHover(new java.awt.Color(38, 38, 38));
        agregarBtn.setEfecto(rojeru_san.rsbutton.RSButtonEffect.EFECTO.RIPPLE);
        agregarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        agregarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        agregarBtn.setIconTextGap(12);
        agregarBtn.setMargin(new java.awt.Insets(2, 6, 2, 14));
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rSButtonEffect4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonEffect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(estadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelTotalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUsuariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUsuariosBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUsuariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUsuariosBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(estadoCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
     
    }//GEN-LAST:event_tablaMouseClicked

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        if(uframe.isShowing()){
          new rojerusan.RSNotifyFade("¡¡Ventana en uso!! ", "Ya se está agregando o editando un usuario, cierre antes esa ventana para continuar", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }else{
            if(uframe == null){
                uframe = new UsuarioFrame();
                uframe.setVisible(true);
            }else{
                uframe = new UsuarioFrame();
                uframe.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int fila = tabla.getSelectedRow();
        String codigo="";
        if(fila<0){
            new rojerusan.RSNotifyFade("¡¡Seleccione Usuario!! ", "Elija primero el usuario que va editar", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }else{
            codigo = tabla.getValueAt(fila, 1).toString();
            if(uframe.isShowing()){
          new rojerusan.RSNotifyFade("¡¡Ventana en uso!! ", "Ya se está agregando o editando un usuario, cierre antes esa ventana para continuar", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }else{
                
                uframe = new UsuarioFrame(codigo);
                uframe.setVisible(true);
        }
                    
                    
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void estadoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoComboItemStateChanged
        int index = estadoCombo.getSelectedIndex();
        if(index == 0 || index==3){
            estadox ="";
        }else if (index ==1){
            estadox="Activo";
        }else {
            estadox="Bloqueado";
        }
    }//GEN-LAST:event_estadoComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.rsbutton.RSButtonEffect agregarBtn;
    private rojeru_san.rsbutton.RSButtonEffect buscarBtn;
    public rojeru_san.rsbutton.RSButtonEffect editBtn;
    private static rojerusan.RSComboBox estadoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private static javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel panelBotones;
    private rojeru_san.rspanel.RSPanelVector panelTotalUsuarios;
    private rojeru_san.rspanel.RSPanelVector panelUsuariosActivos;
    private rojeru_san.rspanel.RSPanelVector panelUsuariosBloqueados;
    private rojeru_san.rsbutton.RSButtonEffect rSButtonEffect4;
    public static rojerusan.RSTableMetro tabla;
    private static javax.swing.JLabel totalUserTxt;
    private static javax.swing.JLabel userActivosTxt;
    private static javax.swing.JLabel userBloqueadosTxt;
    // End of variables declaration//GEN-END:variables

    
    public static void reiniciarDatos(){
        llenarTabla("");
        new rojerusan.RSNotifyFade("¡¡Refresh!! ", "Datos Actualizados!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                           
    }
    public static void reiniciarDatos(String buscarCodigo){
       
        llenarTabla("");
        
        for(int i=0; i<tabla.getRowCount(); i++){
            if(tabla.getValueAt(i, 0).equals(buscarCodigo)){
               tabla.changeSelection(i, 0, false, false);
            }
        }
         estadoCombo.setSelectedIndex(0);
         nombreTxt.setText("");
    }
    
    public static void vaciarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
    }
public static void llenarTabla() {

        try (Connection con = new ConectarCloudcPanel("corporacionagama_mainbigmedic").getCon()) {

            String sql = "call `sp.ConsAllusers` (?)";
            PreparedStatement pst = con.prepareCall(sql);
            pst.setString(1, estadox);
            ResultSet rs = pst.executeQuery();
            vaciarTabla();
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            todos=0;
            activos=0;
            bloqueados=0;
            while (rs.next()) {
                todos++;
                String cod = rs.getString("codigo");
                String est = rs.getString("estado");
                if(est.toLowerCase().contains("activ")){
                    activos++;
                }else{
                    bloqueados++;
                }
                
                modelo.addRow(new Object[]{
                    
                    rs.getString("id"),
                    cod, rs.getString("nombre"), 
                    rs.getString("estado")
                    
                    
                    
                });

            }

            if (modelo.getRowCount() == 0) {
                modelo.addRow(new Object[]{
                    "", "Sin resultados"
                });
            }
        } catch (Exception e) {
            Logger.getLogger(UsuariosPanel.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Error con el manejo de base de datos, contacte con el adm.\n" + e);
        }
        totalUserTxt.setText(todos+"");
        userActivosTxt.setText(activos+"");
        userBloqueadosTxt.setText(bloqueados+"");
    }

    public static void llenarTabla(String text) {

        try (Connection con = new ConectarCloudcPanel("corporacionagama_mainbigmedic").getCon()) {

            String sql = "call `sp.ConsAllusers` (?)";
            PreparedStatement pst = con.prepareCall(sql);
            pst.setString(1, text);
            ResultSet rsx = pst.executeQuery();
            vaciarTabla();
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            todos=0;
            activos=0;
            bloqueados=0;
            while (rsx.next()) {
                todos++;
                String est = rsx.getString("estado");
                String cod = rsx.getString("codigo");
                if(est.toLowerCase().contains("activ")){
                    activos++;
                }else{
                    bloqueados++;
                }
                modelo.addRow(new Object[]{
                    rsx.getString("id"),
                    cod, rsx.getString("nombre"), 
                    rsx.getString("estado")
                });

            }

            if (modelo.getRowCount() == 0) {
                modelo.addRow(new Object[]{
                    "", "Sin resultados"
                });
            }
        } catch (Exception e) {
            Logger.getLogger(UsuariosPanel.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Error con el manejo de base de datos, contacte con el adm.\n" + e);
        }
        totalUserTxt.setText(todos+"");
        userActivosTxt.setText(activos+"");
        userBloqueadosTxt.setText(bloqueados+"");
        
    }

    private void ini() {
        estadoCombo.setVisible(false);
        jLabel3.setVisible(false);
        nombreTxt.setVisible(false);
        buscarBtn.setVisible(false);
    }

}
